# Generated by Django 4.2.25 on 2025-10-22 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workers", "0002_alter_worker_created_at_alter_worker_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_workers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель записи",
            ),
        ),
    ]
