# Generated by Django 4.2.25 on 2025-10-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0003_alter_worker_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="hired_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата приёма"),
        ),
    ]
