name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
    
    - name: Install dependencies
      run: poetry install
    
    - name: Check code formatting with Black
      run: poetry run black --check --diff .
    
    - name: Check imports with isort
      run: poetry run isort --check-only --diff .
      continue-on-error: true
    
    - name: Security check
      run: |
        pip install safety
        poetry export -f requirements.txt | safety check --stdin
      continue-on-error: true