name: Docker Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: hr-workers:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Create .env file for testing
      run: |
        echo "SECRET_KEY=test-secret-key-for-docker" > .env
        echo "DEBUG=True" >> .env
    
    - name: Test Docker Compose
      run: |
        docker compose up -d --wait
        sleep 10
        
        # Test API endpoint
        curl -f http://localhost:8000/api/workers/ || exit 1
        
        # Test admin endpoint
        curl -f http://localhost:8000/admin/ || exit 1
        
        # Show logs for debugging
        docker compose logs web
        
        # Cleanup
        docker compose down -v